pipeline{
    agent any
     tools{
         maven 'maven'
         jdk 'jdk'
}
      
        stages{
            stage('Git-Checkout')
            {
              steps{
                  script{
                        FAILED_STAGE=env.STAGE_NAME
                   bat 'rm -rf CodingChallenge2'
                     git 'https://github.com/sreelakshmi665/awsSpring.git'
                }
            }
            }
             stage('Validate')
        {
            steps{
                script{
                        FAILED_STAGE=env.STAGE_NAME
              bat 'mvn -f CodingChallenge2  clean validate'
                }
            }
        }
        stage('Compile')
        {
            steps{
                script{
                        FAILED_STAGE=env.STAGE_NAME
               bat 'mvn -f CodingChallenge2 compile'
                }
            }
        }
            stage('sonar analysis'){
            steps{
                 script{
                        FAILED_STAGE=env.STAGE_NAME    
                withSonarQubeEnv('sonar-server'){
                    
                        bat 'mvn -f CodingChallenge2 sonar:sonar'
                    
                    }
                }
            }
            }
        
             stage("Quality gate") {
            steps {
                script{
                        FAILED_STAGE=env.STAGE_NAME
                waitForQualityGate abortPipeline: true
                }
            }
        }
            
        stage('Test')
        {
            steps{
                script{
                        FAILED_STAGE=env.STAGE_NAME
                bat 'mvn -f CodingChallenge2 test'
                }
            }
        }
        stage('Package')
        {
            steps{
                script{
                        FAILED_STAGE=env.STAGE_NAME
               bat 'mvn -f CodingChallenge2 package'
                }
            }
        }
        stage('Verify')
        {
            steps{
                script{
                        FAILED_STAGE=env.STAGE_NAME
               bat 'mvn -f CodingChallenge2 verify'
                }
            }
        }
        stage('Install')
        {
            steps{
                script{
                        FAILED_STAGE=env.STAGE_NAME
                bat 'mvn -f CodingChallenge2 install'
                }
            }
        }
      stage('Artifactory')
    {
      steps{
           script{
                        FAILED_STAGE=env.STAGE_NAME
                        
        archiveArtifacts artifacts:'CodingChallenge2/target/*.jar',followSymlinks:false
           }
      }
      }
        
    stage('Deploy-To-Artifactory')
    {
      steps{
           script{
                        FAILED_STAGE=env.STAGE_NAME
                       
        rtUpload(
          serverId:'artifactory-server',
          spec: '''{
          "files": [
            {
              "pattern": "CodingChallenge2/target/*.jar",
              "target": "art-doc-dev-loc"
            }
         ]
    }''',
          
)
  }
}   
    } 

}          
     post {  
         always {  
             echo 'This will always run'  
         }  
         success {  
             echo 'This will run only if successful'
              mail bcc: '', body: "<b>Example</b><br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER} <br> Success!! <br> URL de build: ${env.BUILD_URL}", cc: '', charset: 'UTF-8', from: 'sreelakshmilucky14@gmail.com', mimeType: 'text/html', replyTo: '', subject: "ERROR CI: Project name -> ${env.JOB_NAME}", to: "sreelakshmilucky14@gmail.com"; 
            
       
         }  
         failure {  
             mail bcc: '', body: "<b>Example</b><br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER}<br> Failure!! <br> <br>Build Failed Stage: ${FAILED_STAGE} <br> URL de build: ${env.BUILD_URL}", cc: '', charset: 'UTF-8', from: 'sreelakshmilucky14@gmail.com', mimeType: 'text/html', replyTo: '', subject: "ERROR CI: Project name -> ${env.JOB_NAME}", to: "sreelakshmilucky14@gmail.com";  
         }  
         unstable {  
             echo 'This will run only if the run was marked as unstable'  
         }  
         changed {  
             echo 'This will run only if the state of the Pipeline haschanged'  
             echo 'For example, if the Pipeline was previously failing but is now successful'  
         }  
     }    
}
